# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2055307dab8fcb476d0a03574b8a76cb2070da72a5c250a74b9258768c64d68618e0c5d5f164abc78df5d5496f21a74643d79e865220d0f11e1f39d044f8fc9

test:
  secret_key_base: c4edab243008800ddbe44291a3affe51fe13246b1f9586c2143d6f3871ad1d357f31a1d2ed278651727f9b1e43123ac952f4b00d8e111021b0124ae3372acd01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
